/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package carnival.demo.micronaut


import io.micronaut.runtime.Micronaut
import groovy.transform.CompileStatic


@CompileStatic
class Application {
    static void main(String[] args) {
        Micronaut.run(Application, args)
    }
}
